package com.nodomain.manyface.domain;


public enum Error {

    NONE,
    NETWORK_IS_NOT_AVAILABLE,
    CONNECTION_FAILED,
    EMPTY_LOGIN,
    EMPTY_PROFILE_NAME,
    EMPTY_PASSWORD,
    EMPTY_PASSWORD_CONFIRMATION,
    ILLEGAL_CHARACTERS_IN_LOGIN,
    ILLEGAL_CHARACTERS_IN_PROFILE_NAME,
    ILLEGAL_CHARACTERS_IN_PASSWORD,
    ILLEGAL_CHARACTERS_IN_PASSWORD_CONFIRMATION,
    INCORRECT_PASSWORD_CONFIRMATION,
    ACCOUNT_ALREADY_EXISTS,
    PROFILE_ALREADY_EXISTS,
    INCORRECT_LOGIN_AND_PASSWORD_COMBINATION,
    TOO_MANY_PROFILES,
    FILE_READING_FAILURE
}
